using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Collections.ObjectModel;

namespace ITUmain
{
    public class LoadExampleData
    {
        //public static List<RenameLaterClasses.DeviceType> DataTest = new List<RenameLaterClasses.DeviceType>()
        public static ObservableCollection<RenameLaterClasses.DeviceType> DataTest = new ObservableCollection<RenameLaterClasses.DeviceType>()
        {
            new RenameLaterClasses.Computer() {
                TypeOfDevice = "computer",
                ManufactureNumber = "NX56AL",
                Manufacturer = "HP",
                Name = "Luxeur 5a",
                Condition = "Použitý",
                Price = "25 000 Kč",
                Place = "Prodejna",
                Description = "Lorem ipsum dolor sit amet.",
                Author = "Lorenz",
                Date = DateTime.Now,
                CPU = "i5 6500",
                RAM = "8 GB",
                GPU = "GTX 680",
                Memory = "1 TB",
                Dimensions = "45 x 56 x 50",
                OS = "Windows 10",
                Ports = "2x USB 3.0, 3x USB 2.0"
            },
 new RenameLaterClasses.Computer() {
                TypeOfDevice = "computer",
                ManufactureNumber = "KL846O",
                Manufacturer = "Alien",
                Name = "FpsKiller",
                Condition = "Nový",
                Price = "35 000 Kč",
                Place = "Sklad",
                Description = "Lorem ipsum dolor sit amet.",
                Author = "Pavelka",
                Date = DateTime.Now,
                CPU = "Ryzen 2600",
                RAM = "16 GB",
                GPU = "GTX 1060",
                Memory = "2 TB",
                Dimensions = "45 x 56 x 50",
                OS = "Windows 10",
                Ports = "2x USB 3.0, 3x USB 2.0"
            },
 new RenameLaterClasses.Notebook() {
                TypeOfDevice = "notebook",
                ManufactureNumber = "KLE46A",
                Manufacturer = "Acer",
                Name = "Aspire",
                Condition = "Použitý",
                Price = "9 999 Kč",
                Place = "Prodejna",
                Description = "Lorem ipsum dolor sit amet.",
                Author = "Lorenz",
                Date = DateTime.Now,
                CPU = "i3 3100",
                RAM = "4 GB",
                GPU = "hd450",
                Memory = "500 GB",
                Dimensions = "30 x 40 x 25",
                OS = "Windows 10",
                Ports = "2x USB 3.0, 3x USB 2.0",
                Weight = "2 Kg",
                BatteryCappacity = "18 000 mAh",
                Display = "1366 x 1024",
                Camera = "Front",
                Numpad = "Není",
                FingerPrintReader = "Není"
            },
new RenameLaterClasses.Monitor() {
                TypeOfDevice = "monitor",
                ManufactureNumber = "DE151A",
                Manufacturer = "Dell",
                Name = "Ql22i",
                Condition = "Nový",
                Price = "7500 Kč",
                Place = "Sklad",
                Description = "Lorem ipsum dolor sit amet.",
                Author = "Pavelka",
                Date = DateTime.Now,
                Dimensions = "40 x 50 x 5",
                PanelType = "IPS",
                Resolution = "3840 x 2160",
                Frequency = "120 Hz",
                ResponseTime = "1 ms",
                Connectors = "HDMI, VGA, 2x DVI-D, DP",
                Vesa = "Ano",
                Speakers = "Ano",
                CablesIncluded = "Ano"
            },
 new RenameLaterClasses.Telephone() {
                TypeOfDevice = "telefon",
                ManufactureNumber = "546SD8",
                Manufacturer = "Xiaomi",
                Name = "Mi8",
                Condition = "Nový",
                Price = "9 999 Kč",
                Place = "Prodejna",
                Description = "Lorem ipsum dolor sit amet.",
                Author = "Lorenz",
                Date = DateTime.Now,
                CPU = "Snapdragon 660",
                RAM = "4 GB",
                Display = "OLED",
                Size = "7\"",
                Weight = "150 g",
                DualSim = "Ano",
                SdCard = "Ano",
                Camera = "Ano",
                Colour = "Černá",
                ChargingTime = "1 h"
            },
 new RenameLaterClasses.Telephone()
            {
                TypeOfDevice = "telefon",
                ManufactureNumber = "546SD8",
                Manufacturer = "Xiaomi",
                Name = "Mi9",
                Condition = "Nový",
                Price = "19 999 Kč",
                Place = "Sklad",
                Description = "Lorem ipsum dolor sit amet.",
                Author = "Lorenz",
                Date = DateTime.Now,
                CPU = "Snapdragon 670",
                RAM = "4 GB",
                Display = "OLED",
                Size = "7\"",
                Weight = "150 g",
                DualSim = "Ano",
                SdCard = "Ano",
                Camera = "Ano",
                Colour = "Černá",
                ChargingTime = "1 h"
            },
            new RenameLaterClasses.Monitor()
            {
                TypeOfDevice = "monitor",
                ManufactureNumber = "DLS51A",
                Manufacturer = "Dell",
                Name = "QQ25i",
                Condition = "Použitý",
                Price = "3500 Kč",
                Place = "Sklad",
                Description = "Lorem ipsum dolor sit amet.",
                Author = "Pavelka",
                Date = DateTime.Now,
                Dimensions = "40 x 50 x 5",
                PanelType = "IPS",
                Resolution = "3840 x 2160",
                Frequency = "60 Hz",
                ResponseTime = "1 ms",
                Connectors = "HDMI, VGA, DP",
                Vesa = "Ano",
                Speakers = "Ano",
                CablesIncluded = "Ano"
            },
            new RenameLaterClasses.Computer()
            {
                TypeOfDevice = "computer",
                ManufactureNumber = "N1S6AS",
                Manufacturer = "Acer",
                Name = "Ler 5b",
                Condition = "Zánovní",
                Price = "25 000 Kč",
                Place = "Prodejna",
                Description = "Lorem ipsum dolor sit amet.",
                Author = "Pavelka",
                Date = DateTime.Now,
                CPU = "i5 7500K",
                RAM = "8 GB",
                GPU = "GTX 780",
                Memory = "2 TB",
                Dimensions = "45 x 56 x 50",
                OS = "Windows 10",
                Ports = "2x USB 3.0, 3x USB 2.0"
            },
             new RenameLaterClasses.Monitor()
            {
                TypeOfDevice = "monitor",
                ManufactureNumber = "DLS51A",
                Manufacturer = "Dell",
                Name = "QQ25i",
                Condition = "Použitý",
                Price = "3500 Kč",
                Place = "Sklad",
                Description = "Lorem ipsum dolor sit amet.",
                Author = "Pavelka",
                Date = DateTime.Now,
                Dimensions = "40 x 50 x 5",
                PanelType = "IPS",
                Resolution = "3840 x 2160",
                Frequency = "60 Hz",
                ResponseTime = "1 ms",
                Connectors = "HDMI, VGA, DP",
                Vesa = "Ano",
                Speakers = "Ano",
                CablesIncluded = "Ano"
            },
             new RenameLaterClasses.Telephone()
            {
                TypeOfDevice = "telefon",
                ManufactureNumber = "546SD8",
                Manufacturer = "Xiaomi",
                Name = "Mi9",
                Condition = "Nový",
                Price = "19 999 Kč",
                Place = "Sklad",
                Description = "Lorem ipsum dolor sit amet.",
                Author = "Lorenz",
                Date = DateTime.Now,
                CPU = "Snapdragon 670",
                RAM = "4 GB",
                Display = "OLED",
                Size = "7\"",
                Weight = "150 g",
                DualSim = "Ano",
                SdCard = "Ano",
                Camera = "Ano",
                Colour = "Černá",
                ChargingTime = "1 h"
            }
        };
    }
}
